"""baseline schema

Baseline migration: captures the FULL current schema (agronomy + operations/
traceability layers, 24 tables) exactly as the SQLAlchemy models define it.
Running `alembic upgrade head` on an empty database reproduces what
supabase_schema.sql currently builds. From here on, Alembic is the source of
truth for schema changes — add a new autogenerated revision per model change
(`alembic revision --autogenerate -m "..."` then `alembic upgrade head`).

Revision ID: 49fa233d5c67
Revises:
Create Date: 2026-06-28 23:01:36.777261
"""
from alembic import op
import sqlalchemy as sa


revision = '49fa233d5c67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=255), nullable=False),
    sa.Column('activity_category', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('requires_product', sa.Boolean(), nullable=False),
    sa.Column('requires_photo_evidence', sa.Boolean(), nullable=False),
    sa.Column('default_required_photo_count', sa.Integer(), nullable=False),
    sa.Column('requires_geolocation', sa.Boolean(), nullable=False),
    sa.Column('requires_surface_area', sa.Boolean(), nullable=False),
    sa.Column('requires_dose', sa.Boolean(), nullable=False),
    sa.Column('requires_weather_snapshot', sa.Boolean(), nullable=False),
    sa.Column('default_follow_up_days', sa.Integer(), nullable=True),
    sa.Column('recommended_frequency', sa.String(length=64), nullable=True),
    sa.Column('carbon_factor_value', sa.Float(), nullable=True),
    sa.Column('carbon_factor_unit', sa.String(length=32), nullable=True),
    sa.Column('carbon_category', sa.String(length=64), nullable=True),
    sa.Column('carbon_methodology_note', sa.Text(), nullable=True),
    sa.Column('carbon_factor_source', sa.String(length=255), nullable=True),
    sa.Column('carbon_factor_version', sa.String(length=32), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_active'), 'activities', ['active'], unique=False)
    op.create_index(op.f('ix_activities_activity_name'), 'activities', ['activity_name'], unique=False)
    op.create_table('assignees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignees_active'), 'assignees', ['active'], unique=False)
    op.create_index(op.f('ix_assignees_email'), 'assignees', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('old_values_json', sa.JSON(), nullable=True),
    sa.Column('new_values_json', sa.JSON(), nullable=True),
    sa.Column('changed_by', sa.String(length=128), nullable=True),
    sa.Column('changed_by_email', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('farms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('municipality', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_type', sa.String(length=32), nullable=False),
    sa.Column('active_ingredient', sa.String(length=255), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('restricted', sa.Boolean(), nullable=False),
    sa.Column('prohibited', sa.Boolean(), nullable=False),
    sa.Column('default_dose_value', sa.Float(), nullable=True),
    sa.Column('default_dose_unit', sa.String(length=32), nullable=True),
    sa.Column('min_dose_value', sa.Float(), nullable=True),
    sa.Column('max_dose_value', sa.Float(), nullable=True),
    sa.Column('application_method', sa.String(length=128), nullable=True),
    sa.Column('safety_notes', sa.Text(), nullable=True),
    sa.Column('regenerative_notes', sa.Text(), nullable=True),
    sa.Column('carbon_factor_value', sa.Float(), nullable=True),
    sa.Column('carbon_factor_unit', sa.String(length=32), nullable=True),
    sa.Column('carbon_factor_source', sa.String(length=255), nullable=True),
    sa.Column('carbon_factor_version', sa.String(length=32), nullable=True),
    sa.Column('carbon_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_active'), 'products', ['active'], unique=False)
    op.create_index(op.f('ix_products_product_name'), 'products', ['product_name'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_datetime', sa.DateTime(), nullable=False),
    sa.Column('related_work_order_id', sa.Integer(), nullable=True),
    sa.Column('related_execution_record_id', sa.Integer(), nullable=True),
    sa.Column('related_product_id', sa.Integer(), nullable=True),
    sa.Column('related_activity_id', sa.Integer(), nullable=True),
    sa.Column('related_photo_ids', sa.JSON(), nullable=True),
    sa.Column('carbon_kgco2e', sa.Float(), nullable=True),
    sa.Column('weather_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_entity_id'), 'timeline_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_entity_type'), 'timeline_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_datetime'), 'timeline_events', ['event_datetime'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('telegram_user_id', sa.String(length=64), nullable=True),
    sa.Column('whatsapp_phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    op.create_index(op.f('ix_users_whatsapp_phone'), 'users', ['whatsapp_phone'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope_type', sa.String(length=16), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('lot_code', sa.String(length=64), nullable=False),
    sa.Column('crop_type', sa.String(length=64), nullable=False),
    sa.Column('planted_at', sa.DateTime(), nullable=True),
    sa.Column('estimated_age_months', sa.Integer(), nullable=True),
    sa.Column('polygon_geojson', sa.JSON(), nullable=True),
    sa.Column('centroid_latitude', sa.Float(), nullable=True),
    sa.Column('centroid_longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_farm_id'), 'lots', ['farm_id'], unique=False)
    op.create_index(op.f('ix_lots_lot_code'), 'lots', ['lot_code'], unique=False)
    op.create_table('field_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('zone_name', sa.String(length=64), nullable=False),
    sa.Column('centroid_latitude', sa.Float(), nullable=True),
    sa.Column('centroid_longitude', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_zones_lot_id'), 'field_zones', ['lot_id'], unique=False)
    op.create_index(op.f('ix_field_zones_zone_name'), 'field_zones', ['zone_name'], unique=False)
    op.create_table('agave_passports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_code', sa.String(length=64), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('lot_name', sa.String(length=255), nullable=True),
    sa.Column('zone_name', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('estimated_age_months', sa.Integer(), nullable=True),
    sa.Column('health_status', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('last_inspection_at', sa.DateTime(), nullable=True),
    sa.Column('next_inspection_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['field_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agave_passports_farm_id'), 'agave_passports', ['farm_id'], unique=False)
    op.create_index(op.f('ix_agave_passports_lot_id'), 'agave_passports', ['lot_id'], unique=False)
    op.create_index(op.f('ix_agave_passports_passport_code'), 'agave_passports', ['passport_code'], unique=True)
    op.create_index(op.f('ix_agave_passports_risk_level'), 'agave_passports', ['risk_level'], unique=False)
    op.create_index(op.f('ix_agave_passports_zone_id'), 'agave_passports', ['zone_id'], unique=False)
    op.create_table('ops_weather_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('weather_datetime', sa.DateTime(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('rainfall_current', sa.Float(), nullable=True),
    sa.Column('rainfall_probability', sa.Float(), nullable=True),
    sa.Column('rainfall_last_24h', sa.Float(), nullable=True),
    sa.Column('rainfall_next_24h', sa.Float(), nullable=True),
    sa.Column('temperature_current', sa.Float(), nullable=True),
    sa.Column('temperature_min', sa.Float(), nullable=True),
    sa.Column('temperature_max', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('raw_payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['field_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('passport_id', sa.Integer(), nullable=True),
    sa.Column('source_channel', sa.String(length=32), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('original_caption', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('image_type', sa.String(length=32), nullable=False),
    sa.Column('plant_condition', sa.String(length=32), nullable=False),
    sa.Column('suspected_issue', sa.String(length=255), nullable=True),
    sa.Column('diagnosis', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('visible_symptoms_json', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('recommended_next_step', sa.Text(), nullable=True),
    sa.Column('needs_human_review', sa.Boolean(), nullable=False),
    sa.Column('human_verified', sa.Boolean(), nullable=False),
    sa.Column('human_correction', sa.Text(), nullable=True),
    sa.Column('human_validation_status', sa.String(length=16), nullable=False),
    sa.Column('human_corrected_label', sa.String(length=255), nullable=True),
    sa.Column('human_notes', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.String(length=128), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('manual_note', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('process_type', sa.String(length=48), nullable=True),
    sa.Column('responsible_person', sa.String(length=128), nullable=True),
    sa.Column('follow_up_needed', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('agronomist_notes', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('escalation_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['agave_passports.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_observations_escalation_status'), 'field_observations', ['escalation_status'], unique=False)
    op.create_index(op.f('ix_field_observations_event_type'), 'field_observations', ['event_type'], unique=False)
    op.create_index(op.f('ix_field_observations_farm_id'), 'field_observations', ['farm_id'], unique=False)
    op.create_index(op.f('ix_field_observations_follow_up_needed'), 'field_observations', ['follow_up_needed'], unique=False)
    op.create_index(op.f('ix_field_observations_human_validation_status'), 'field_observations', ['human_validation_status'], unique=False)
    op.create_index(op.f('ix_field_observations_lot_id'), 'field_observations', ['lot_id'], unique=False)
    op.create_index(op.f('ix_field_observations_observed_at'), 'field_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_field_observations_passport_id'), 'field_observations', ['passport_id'], unique=False)
    op.create_index(op.f('ix_field_observations_review_status'), 'field_observations', ['review_status'], unique=False)
    op.create_index(op.f('ix_field_observations_severity'), 'field_observations', ['severity'], unique=False)
    op.create_index(op.f('ix_field_observations_status'), 'field_observations', ['status'], unique=False)
    op.create_index(op.f('ix_field_observations_user_id'), 'field_observations', ['user_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_code', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('agave_passport_id', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('planned_start_date', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_email', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('secure_access_token_hash', sa.String(length=128), nullable=True),
    sa.Column('secure_link_expires_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=128), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('required_photo_evidence_count', sa.Integer(), nullable=False),
    sa.Column('geolocation_required', sa.Boolean(), nullable=False),
    sa.Column('manual_note_required', sa.Boolean(), nullable=False),
    sa.Column('weather_capture_required', sa.Boolean(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agave_passport_id'], ['agave_passports.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['assignees.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['field_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_assigned_to_id'), 'work_orders', ['assigned_to_id'], unique=False)
    op.create_index(op.f('ix_work_orders_field_id'), 'work_orders', ['field_id'], unique=False)
    op.create_index(op.f('ix_work_orders_lot_id'), 'work_orders', ['lot_id'], unique=False)
    op.create_index(op.f('ix_work_orders_secure_access_token_hash'), 'work_orders', ['secure_access_token_hash'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    op.create_index(op.f('ix_work_orders_work_order_code'), 'work_orders', ['work_order_code'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('recipient', sa.String(length=128), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['field_observations.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['agave_passports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_observation_id'), 'alerts', ['observation_id'], unique=False)
    op.create_index(op.f('ix_alerts_passport_id'), 'alerts', ['passport_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('escalations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=128), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('message_body', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['field_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_observation_id'), 'escalations', ['observation_id'], unique=False)
    op.create_table('human_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('original_diagnosis', sa.String(length=255), nullable=True),
    sa.Column('corrected_label', sa.String(length=255), nullable=True),
    sa.Column('original_confidence', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validated_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['field_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_human_validations_observation_id'), 'human_validations', ['observation_id'], unique=False)
    op.create_table('model_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['field_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_outputs_observation_id'), 'model_outputs', ['observation_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_id', sa.Integer(), nullable=True),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.String(length=128), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('needs_approval', sa.Boolean(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['field_observations.id'], ),
    sa.ForeignKeyConstraint(['passport_id'], ['agave_passports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('ix_tasks_observation_id'), 'tasks', ['observation_id'], unique=False)
    op.create_index(op.f('ix_tasks_passport_id'), 'tasks', ['passport_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity_percent', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('recent_rain_mm', sa.Float(), nullable=True),
    sa.Column('heat_risk', sa.String(length=16), nullable=True),
    sa.Column('drought_risk', sa.String(length=16), nullable=True),
    sa.Column('weather_source', sa.String(length=64), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['field_observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_snapshots_observation_id'), 'weather_snapshots', ['observation_id'], unique=False)
    op.create_table('work_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('planned_surface_area_value', sa.Float(), nullable=True),
    sa.Column('planned_surface_area_unit', sa.String(length=16), nullable=True),
    sa.Column('planned_dose_value', sa.Float(), nullable=True),
    sa.Column('planned_dose_unit', sa.String(length=32), nullable=True),
    sa.Column('planned_total_product_value', sa.Float(), nullable=True),
    sa.Column('planned_total_product_unit', sa.String(length=16), nullable=True),
    sa.Column('required_photo_count', sa.Integer(), nullable=False),
    sa.Column('requires_geolocation', sa.Boolean(), nullable=False),
    sa.Column('requires_weather_snapshot', sa.Boolean(), nullable=False),
    sa.Column('requires_manual_note', sa.Boolean(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('planned_carbon_factor_value', sa.Float(), nullable=True),
    sa.Column('planned_carbon_factor_unit', sa.String(length=32), nullable=True),
    sa.Column('planned_carbon_kgco2e', sa.Float(), nullable=True),
    sa.Column('carbon_factor_snapshot', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_items_status'), 'work_order_items', ['status'], unique=False)
    op.create_index(op.f('ix_work_order_items_work_order_id'), 'work_order_items', ['work_order_id'], unique=False)
    op.create_table('execution_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('work_order_item_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('actual_surface_area_value', sa.Float(), nullable=True),
    sa.Column('actual_surface_area_unit', sa.String(length=16), nullable=True),
    sa.Column('actual_dose_value', sa.Float(), nullable=True),
    sa.Column('actual_dose_unit', sa.String(length=32), nullable=True),
    sa.Column('actual_total_product_value', sa.Float(), nullable=True),
    sa.Column('actual_total_product_unit', sa.String(length=16), nullable=True),
    sa.Column('execution_started_at', sa.DateTime(), nullable=True),
    sa.Column('execution_completed_at', sa.DateTime(), nullable=True),
    sa.Column('responsible_person', sa.String(length=128), nullable=True),
    sa.Column('submitted_by_name', sa.String(length=128), nullable=True),
    sa.Column('submitted_by_email', sa.String(length=255), nullable=True),
    sa.Column('manual_note', sa.Text(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_accuracy', sa.Float(), nullable=True),
    sa.Column('gps_captured_at', sa.DateTime(), nullable=True),
    sa.Column('weather_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('weather_snapshot_status', sa.String(length=16), nullable=False),
    sa.Column('actual_carbon_kgco2e', sa.Float(), nullable=True),
    sa.Column('carbon_factor_snapshot', sa.JSON(), nullable=True),
    sa.Column('carbon_calculation_status', sa.String(length=20), nullable=False),
    sa.Column('carbon_override_value', sa.Float(), nullable=True),
    sa.Column('carbon_override_reason', sa.Text(), nullable=True),
    sa.Column('carbon_override_user', sa.String(length=128), nullable=True),
    sa.Column('carbon_override_at', sa.DateTime(), nullable=True),
    sa.Column('compliance_status', sa.String(length=20), nullable=False),
    sa.Column('is_revision_of_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['is_revision_of_id'], ['execution_records.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['weather_snapshot_id'], ['ops_weather_snapshots.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.ForeignKeyConstraint(['work_order_item_id'], ['work_order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_records_compliance_status'), 'execution_records', ['compliance_status'], unique=False)
    op.create_index(op.f('ix_execution_records_work_order_id'), 'execution_records', ['work_order_id'], unique=False)
    op.create_index(op.f('ix_execution_records_work_order_item_id'), 'execution_records', ['work_order_item_id'], unique=False)
    op.create_table('photo_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.Column('work_order_item_id', sa.Integer(), nullable=True),
    sa.Column('execution_record_id', sa.Integer(), nullable=True),
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('agave_passport_id', sa.Integer(), nullable=True),
    sa.Column('gps_latitude', sa.Float(), nullable=True),
    sa.Column('gps_longitude', sa.Float(), nullable=True),
    sa.Column('gps_accuracy', sa.Float(), nullable=True),
    sa.Column('gps_source', sa.String(length=16), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('uploaded_by', sa.String(length=128), nullable=True),
    sa.Column('manual_note', sa.Text(), nullable=True),
    sa.Column('weather_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agave_passport_id'], ['agave_passports.id'], ),
    sa.ForeignKeyConstraint(['execution_record_id'], ['execution_records.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['farms.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.id'], ),
    sa.ForeignKeyConstraint(['weather_snapshot_id'], ['ops_weather_snapshots.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.ForeignKeyConstraint(['work_order_item_id'], ['work_order_items.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['field_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_evidence_execution_record_id'), 'photo_evidence', ['execution_record_id'], unique=False)
    op.create_index(op.f('ix_photo_evidence_work_order_id'), 'photo_evidence', ['work_order_id'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_record_id', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=128), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('correction_requested', sa.Boolean(), nullable=False),
    sa.Column('correction_due_date', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['execution_record_id'], ['execution_records.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['assignees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_execution_record_id'), 'reviews', ['execution_record_id'], unique=False)
    op.create_index(op.f('ix_reviews_review_status'), 'reviews', ['review_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_review_status'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_execution_record_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_photo_evidence_work_order_id'), table_name='photo_evidence')
    op.drop_index(op.f('ix_photo_evidence_execution_record_id'), table_name='photo_evidence')
    op.drop_table('photo_evidence')
    op.drop_index(op.f('ix_execution_records_work_order_item_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_work_order_id'), table_name='execution_records')
    op.drop_index(op.f('ix_execution_records_compliance_status'), table_name='execution_records')
    op.drop_table('execution_records')
    op.drop_index(op.f('ix_work_order_items_work_order_id'), table_name='work_order_items')
    op.drop_index(op.f('ix_work_order_items_status'), table_name='work_order_items')
    op.drop_table('work_order_items')
    op.drop_index(op.f('ix_weather_snapshots_observation_id'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_passport_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_observation_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_date'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_model_outputs_observation_id'), table_name='model_outputs')
    op.drop_table('model_outputs')
    op.drop_index(op.f('ix_human_validations_observation_id'), table_name='human_validations')
    op.drop_table('human_validations')
    op.drop_index(op.f('ix_escalations_observation_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_passport_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_observation_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_work_orders_work_order_code'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_secure_access_token_hash'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_lot_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_field_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_assigned_to_id'), table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_field_observations_user_id'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_status'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_severity'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_review_status'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_passport_id'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_observed_at'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_lot_id'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_human_validation_status'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_follow_up_needed'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_farm_id'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_event_type'), table_name='field_observations')
    op.drop_index(op.f('ix_field_observations_escalation_status'), table_name='field_observations')
    op.drop_table('field_observations')
    op.drop_table('ops_weather_snapshots')
    op.drop_index(op.f('ix_agave_passports_zone_id'), table_name='agave_passports')
    op.drop_index(op.f('ix_agave_passports_risk_level'), table_name='agave_passports')
    op.drop_index(op.f('ix_agave_passports_passport_code'), table_name='agave_passports')
    op.drop_index(op.f('ix_agave_passports_lot_id'), table_name='agave_passports')
    op.drop_index(op.f('ix_agave_passports_farm_id'), table_name='agave_passports')
    op.drop_table('agave_passports')
    op.drop_index(op.f('ix_field_zones_zone_name'), table_name='field_zones')
    op.drop_index(op.f('ix_field_zones_lot_id'), table_name='field_zones')
    op.drop_table('field_zones')
    op.drop_index(op.f('ix_lots_lot_code'), table_name='lots')
    op.drop_index(op.f('ix_lots_farm_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_users_whatsapp_phone'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_timeline_events_event_datetime'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_entity_type'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_entity_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_products_product_name'), table_name='products')
    op.drop_index(op.f('ix_products_active'), table_name='products')
    op.drop_table('products')
    op.drop_table('farms')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_assignees_email'), table_name='assignees')
    op.drop_index(op.f('ix_assignees_active'), table_name='assignees')
    op.drop_table('assignees')
    op.drop_index(op.f('ix_activities_activity_name'), table_name='activities')
    op.drop_index(op.f('ix_activities_active'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
