"""add seasons table

Revision ID: 6e1219fdb59c
Revises: 49fa233d5c67
Create Date: 2026-06-28 23:18:16.551820
"""
from alembic import op
import sqlalchemy as sa


revision = '6e1219fdb59c'
down_revision = '49fa233d5c67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_active'), 'seasons', ['active'], unique=False)
    op.create_index(op.f('ix_seasons_name'), 'seasons', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seasons_name'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_active'), table_name='seasons')
    op.drop_table('seasons')
    # ### end Alembic commands ###
