"""add organizations, members, invitations (RBAC)

Revision ID: b4b8620239bc
Revises: b2c3d4e5f6a7
Create Date: 2026-06-30 12:37:23.347447
"""
from alembic import op
import sqlalchemy as sa


revision = 'b4b8620239bc'
down_revision = 'b2c3d4e5f6a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_is_active'), 'organizations', ['is_active'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=True),
    sa.Column('invited_role', sa.String(length=24), nullable=False),
    sa.Column('invited_permissions', sa.JSON(), nullable=True),
    sa.Column('invited_data_scope', sa.String(length=16), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_invited_email'), 'invitations', ['invited_email'], unique=False)
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('can_invite_members', sa.Boolean(), nullable=False),
    sa.Column('can_create_work_orders', sa.Boolean(), nullable=False),
    sa.Column('can_assign_work_orders', sa.Boolean(), nullable=False),
    sa.Column('can_review_work_orders', sa.Boolean(), nullable=False),
    sa.Column('can_manage_catalogs', sa.Boolean(), nullable=False),
    sa.Column('can_view_reports', sa.Boolean(), nullable=False),
    sa.Column('can_view_labor_analytics', sa.Boolean(), nullable=False),
    sa.Column('can_manage_org_settings', sa.Boolean(), nullable=False),
    sa.Column('can_manage_members', sa.Boolean(), nullable=False),
    sa.Column('can_export_data', sa.Boolean(), nullable=False),
    sa.Column('data_scope', sa.String(length=16), nullable=False),
    sa.Column('scope_ranch_ids', sa.JSON(), nullable=True),
    sa.Column('scope_lot_ids', sa.JSON(), nullable=True),
    sa.Column('scope_assignee_emails', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_members_app_user_id'), 'organization_members', ['app_user_id'], unique=False)
    op.create_index(op.f('ix_organization_members_is_active'), 'organization_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_organization_members_organization_id'), 'organization_members', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_members_role'), 'organization_members', ['role'], unique=False)
    op.add_column('app_users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_app_users_organization_id'), 'app_users', ['organization_id'], unique=False)
    op.add_column('work_orders', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_work_orders_organization_id'), 'work_orders', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_organization_id'), table_name='work_orders')
    op.drop_column('work_orders', 'organization_id')
    op.drop_index(op.f('ix_app_users_organization_id'), table_name='app_users')
    op.drop_column('app_users', 'organization_id')
    op.drop_index(op.f('ix_organization_members_role'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_organization_id'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_is_active'), table_name='organization_members')
    op.drop_index(op.f('ix_organization_members_app_user_id'), table_name='organization_members')
    op.drop_table('organization_members')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_invited_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_active'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
